### ISSUE TITLE
Node SQS sample templates are missing mandatory SQS polling policy

### ISSUE THREAD

**Issue by danielg-cf** [aws/aws-sam-cli-app-templates#138]
In order for Lambda to be able to poll from an SQS queue, we must specify the `SQSPollerPolicy` policy, pointing to the relevant SQS queue:
```yaml
Policies:
  - SQSPollerPolicy:
      QueueName: !GetAtt SimpleQueue.QueueName

```
This policy is missing in all SQS sample templates, thus `sam deploy` always fails with the following CloudFormation error:
```
The followingfailed to create: [SQSPayloadLoggerSQSQueueEvent].Resource handlermessage: "Modelfailed (#/EventSourceArn:failed validationconstraint for keyword[pattern])" (RequestToken:9de0e5cc-cd9f-fc71-6a75-7abfb2088f62,HandlerErrorCode:InvalidRequest)
```
