### ISSUE TITLE
HttpApi template wanted

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sam-cli-app-templates#144]
Hoping to see something like:

```
Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY
```

(ins)[hendry@t14s aws-sam-cli-app-templates]$ rg HttpApi
./python3.9/cookiecutter-aws-sam-step-functions-etl-python/.gitignore: line 171: error parsing glob '{{cookiecutter.project_name}}/*_output.yaml': nested alternate groups are not allowed
