### ISSUE TITLE
Feature request: Add AWS Budget CFN resources to the existing sam cli app templates

### ISSUE THREAD

**Issue by pputhran** [aws/aws-sam-cli-app-templates#268]
### Describe your idea/feature/enhancement

**Idea:** Include AWS Budgets CloudFormation resources in the existing cookie cutter SAM CLI application templates. 

Customers/users who create and deploy the Serverless applications using the sam init calls might accidentally run into [runaway/infinite loops scenarios](https://docs.aws.amazon.com/lambda/latest/operatorguide/recursive-runaway.html) which could lead into unexpected increased costs.  Having AWS Budgets configured and deployed along with Serverless services could help alert and notify customers when they are close to or about to breach the given threshold. 

### Proposal

The proposal is to include AWS Budget CFN resources as part of this cookie cutter sample that can alert customers if they exceed 80% of the initial budget for the given AWS Serverless services. 

### Additional Details

Sample AWS Budgets CFN resources for AWS Lambda Service

```
Parameters:
  EmailAddress:
    Type: String

...
  BudgetExample:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetLimit:
          Amount: 100
          Unit: USD
        TimeUnit: MONTHLY
        BudgetName: Serverless-budgets
        BudgetType: COST
        CostFilters:
          Service:
            - AWS Lambda
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            ThresholdType: PERCENTAGE
            Threshold: 90
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailAddress
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
          Subscribers:
          - SubscriptionType: EMAIL
            Address: !Ref EmailAddress
```
